config/routes.rb
Rails.application.routes.draw do
  # Rutas para el controlador DocumentaryController
  get 'documentary/index' => 'documentary#index'
  post 'documentary/create' => 'documentary#create'
  get 'documentary/new' => 'documentary#new'

  # Rutas para el controlador SerialController
  get 'serial/index' => 'serial#index'
  post 'serial/create' => 'serial#create'
  get 'serial/new' => 'serial#new'

  # Rutas para el controlador MovieController
  get 'movie/index' => 'movie#index'
  post 'movie/create' => 'movie#create'
  get 'movie/new' => 'movie#new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Define la ruta de la página principal ("/")
  root 'movie#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentaryfilm.rb
class Documentaryfilm < ApplicationRecord
    validates :name,presence: true
    validates :synopsis,presence: true
    validates :director,presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name,presence: true
    validates :synopsis,presence: true
    validates :director,presence: true
end

app/models/serial.rb
class Serial < ApplicationRecord
    validates :name,presence: true
    validates :synopsis,presence: true
    validates :director,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_controller.rb
class DocumentaryController < ApplicationController
  def index
      @documentaries = Documentaryfilm.all
  end
  def new
      @documentaryfilm = Documentaryfilm.new
  end
  def create
    @documentaryfilm = Documentaryfilm.new(documentary_params)
    if @documentaryfilm.save
      redirect_to documentary_index_path
    else
      render :new
    end
  end

  private

  def documentary_params
    params.require(:documentaryfilm).permit( :name, :synopsis, :director)
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
    def index
  @movies = Movie.all
  end
  def new 
        @movie = Movie.new
  end
  def create
    @movie=Movie.new(movie_params)
    if @movie.save
      redirect_to movie_index_path
    else
      render :new
    end
  end
private
  def movie_params
    params.require(:movie).permit( :name, :synopsis, :director)
  end
end

app/controllers/serial_controller.rb
class SerialController < ApplicationController
  def index
    @serials = Serial.all
  end
  def new
    @serial = Serial.new
  end
  def create
    @serial = Serial.new(serial_params)
    if @serial.save
      redirect_to serial_index_path
    else
      render :new
    end
  end
  private

  def serial_params
    params.require(:serial).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_helper.rb
module DocumentaryHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/serial_helper.rb
module SerialHelper
end

app/views/documentary/create.html.erb
<h1>Documentary#create</h1>
<p>Find me in app/views/documentary/create.html.erb</p>

app/views/documentary/index.html.erb
<h1>Documentary#index</h1>
<p>Find me in app/views/documentary/index.html.erb</p>




 <% @documentaries.each do |movie| %>
 <p>Docu: <%= movie.name %></p>
 <p>Synopsis: <%= movie.synopsis %></p>
 <p>Director: <%= movie.director %></p>
<% end %>

app/views/documentary/new.html.erb
<h1>Documentary#new</h1>
<p>Find me in app/views/documentary/new.html.erb</p>
<h1>New Documentary</h1>
<%= form_with model: @documentaryfilm, url: documentary_create_path, method: :post do |form| %>
    <div>
<%= form.label :name, "Nombre de la pelicula" %>
<%= form.text_field :name %>    </div>
    <div>
<%= form.label :synopsis, "Sinopspis" %>
<%= form.text_field :synopsis %>    </div>
    <div>
<%= form.label :director, "Nombre del director" %>
<%= form.text_field :director %>    </div>
    <div>
        <%= form.submit "Guardar" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Films</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">FILMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">           
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Movies
          </a>
          <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="/movie/index">Index</a></li>  
          <li><a class="dropdown-item" href="/movie/new">New</a></li>       
          </ul>
        </li>
      </ul>
    </div>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">           
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Serial
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/serial/index">index</a></li>
                 <li><a class="dropdown-item" href="/serial/new">New</a></li>   
                    </ul>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">           
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Documentary
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/documentary/index">Index</a></li>  
            <li><a class="dropdown-item" href="/documentary/new">New</a></li>                   
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/movie/create.html.erb
<h1>Movie#create</h1>
<p>Find me in app/views/movie/create.html.erb</p>

app/views/movie/index.html.erb
<h1>Movie#index</h1>
<p>Find me in app/views/movie/index.html.erb</p>


<% @movies.each do |movie| %>
    <p>Movie: <%= movie.name %></p>
    <p>Synopsis: <%= movie.synopsis %></p>
    <p>Director: <%= movie.director %></p>
<% end %>
<h1>Movies</h1>
<%= @movies.all%>

app/views/movie/new.html.erb
<h1>Movie#new</h1>
<p>Find me in app/views/movie/new.html.erb</p>
<h1>New Movie</h1>
<%= form_with model: @movie, url: movie_create_path, method: :post do |form| %>
    <div>
<%= form.label :name, "Nombre de la pelicula" %>
<%= form.text_field :name %>    </div>
    <div>
<%= form.label :synopsis, "Sinopspis" %>
<%= form.text_field :synopsis %>    </div>
    <div>
<%= form.label :director, "Nombre del director" %>
<%= form.text_field :director %>    </div>
    <div>
        <%= form.submit "Guardar" %>
    </div>
<% end %>

app/views/serial/create.html.erb
<h1>Serial#create</h1>
<p>Find me in app/views/serial/create.html.erb</p>

app/views/serial/index.html.erb
<h1>Serial#index</h1>
<p>Find me in app/views/serial/index.html.erb</p>
<% @serials.each do |movie| %>
    <p>Serial: <%= movie.name %></p>
    <p>Synopsis: <%= movie.synopsis %></p>
    <p>Director: <%= movie.director %></p>
<% end %>

<%= @serials.all%>

app/views/serial/new.html.erb
<h1>Serial#new</h1>
<p>Find me in app/views/serial/new.html.erb</p>
<%= form_with model: @serial ,url: serial_create_path, method: :post do |form| %>
    <div>
    <%= form.label :name, "Nombre de la serie" %>
        <%= form.text_field :name %>
    </div>
    <div>
    <%= form.label :synopsis, "Sinopspis" %>
    <%= form.text_field :synopsis %>
    </div>
    <div>
    <%= form.label :director, "Nombre del director" %>
    <%= form.text_field :director %>
    </div>
    <div>
    <%= form.submit "Guardar" %>
    </div>
<%end%>